name: caller
run-name: caller
on:
    workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/main.yml
    with:
      config-path: ./.github/workflows/labeler.yml
    secrets: inherit